from vocab_api import Word,get_list
import json
import genanki

def vocab_list_to_anki(url,name="default"):
    l = get_list(url)
    d = {}
    for i in l:
        d[i] = Word(i).as_dict()
    for i in d:
        d[i]['short_desc'] = ''.join(d[i]['short_desc'])
        d[i]['long_desc'] = ''.join(d[i]['long_desc'])
        d[i]['similardef'] = ''.join(d[i]['similardef'])

    
    words = [word for word in d.keys()]
    base = {}
    for word in words:
        base[word]={}
        base[word]['dictionary_form'] = d[word]['word']
        base[word]['senses'] = d[word]['short_desc']+"\n"+d[word]['long_desc']
        base[word]['sentences'] = d[word]['similardef']
    style = """
    .card {
    font-family: times;
    font-size: 15px;
    color: black;
    background-color: white;
        }
    .card1 { background-color:Lavender;font-size: 15px; }
    """
    my_model = genanki.Model(
  1607392319,
  'Simple Model',
  fields=[
    {'name': 'Question'},
    {'name': 'Answer'},
      {'name' : 'Sentences'}
  ],
  templates=[
    {
      'name': 'Card 1',
      'qfmt': '{{Question}}',
      'afmt': '{{FrontSide}}<hr id="answer">{{Answer}}<br></br> {{Sentences}}',
    }
  ],
    css = style)

    my_deck = genanki.Deck(2059400110,name=name,description='autogenerated')
    for key in base.keys():
        entry = base[key]
        card = genanki.Note(model = my_model,
                       fields = [entry['dictionary_form'],
                                 entry['senses'],
                                 entry['sentences']
                                ])
        my_deck.add_note(card)
    genanki.Package(my_deck).write_to_file(name+".apkg")

#vocab_list_to_anki(url="https://www.vocabulary.com/lists/7897298",name="Kaplan tests review")
